name: "Build & Push to Cachix"
on:
  pull_request:
  push:
jobs:
  cachix:
    strategy:
      matrix:
        # os: [ubuntu-24.04, ubuntu-24.04-arm]
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: rpypkgs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # Check everything that is known to build.
    - run: nix flake check
