name: "Build & Push to Cachix"
on:
  pull_request:
  push:
jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - uses: DeterminateSystems/magic-nix-cache-action@v7
    - uses: cachix/cachix-action@v15
      with:
        name: rpypkgs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # Checks PyPy and some others.
    - run: nix flake check
    # PyGirl requires SDL integration.
    - run: nix build .#pygirl
