name: "Build & Push to Cachix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - uses: DeterminateSystems/magic-nix-cache-action@v7
    - uses: cachix/cachix-action@v15
      with:
        name: rpypkgs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # Can't do `nix flake check` because Pixie and Topaz are broken.
    # DIVSPL has a working check.
    - run: nix build .#divspl
    # PyGirl requires SDL integration.
    - run: nix build .#pygirl
    # This is why we're all here, isn't it?
    - run: nix build .#pypy2
    # - run: nix build .#pypy3
